- name: Arch Init Playbook - Stage Two - Dotfiles
  gather_facts: no
  hosts: localhost

  tasks:

    - name: Install Emacs <emacs>
      become: yes
      pacman:
        name: emacs
        state: present
      tags:
        - dotfile

    - name: Check .emacs.d directory
      stat:
        path: ~/.emacs.d
      register: emacs_folder
      tags:
        - dotfile

    - name: Clone .emacs.d repository
      git:
        repo: git@github.com:curelesss/.emacs.d.git
        dest: "~/.emacs.d"
      when: emacs_folder.stat.exists == False
      tags:
        - dotfile

    - name: Check .dotfiles directory
      stat:
        path: ~/.dotfiles
      register: dotfiles_folder
      tags:
        - dotfile

    - name: Clone .dotfiles repository <dotfile.clone.dotfiles>
      git:
        repo: git@github.com:curelesss/.dotfiles.git
        dest: "~/.dotfiles"
      when: dotfiles_folder.stat.exists == False
      tags:
        - dotfile
